'use client';
import React, { useState, useMemo } from 'react';
import { useApexStore } from '@/store/apex-store';
import { SectionHeader } from '@/components/shared/SectionHeader';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { MetricCard } from '@/components/shared/MetricCard';
import { DataTable } from '@/components/shared/DataTable';
import {
  Building2, Plus, Search, Globe, Truck, Users,
  Shield, AlertTriangle, ChevronRight, X, CheckCircle2, RefreshCw
} from 'lucide-react';
import { formatNumber, timeAgo, regionLabel, cn } from '@/lib/utils';
import { completePairing, initiatePairing, suspendTenant, reactivateTenant } from '@/lib/pairing-engine';
import type { Tenant, RegionCode } from '@/types';

// ─── Pairing Modal ───────────────────────────────────────────────────────────
function PairingModal({ onClose, onSuccess }: { onClose: () => void; onSuccess: () => void }) {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [code, setCode] = useState('');
  const [registrationId, setRegistrationId] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [details, setDetails] = useState({
    companyName: '', region: 'EU' as RegionCode, contactEmail: '',
    fleetName: '', vehicleCount: 50, plan: 'growth' as 'starter' | 'growth' | 'enterprise',
  });
  const { addTenant, addFleet, addAlert } = useApexStore();

  const handleInitiate = async () => {
    setError('');
    setLoading(true);
    try {
      const res = await initiatePairing(code);
      if (!res.success) { setError(res.error || 'Failed'); return; }
      setRegistrationId(res.registrationId!);
      setStep(2);
    } finally { setLoading(false); }
  };

  const handleComplete = async () => {
    setError('');
    setLoading(true);
    try {
      const res = await completePairing(registrationId, details);
      if (!res.success) { setError(res.error || 'Failed'); return; }
      // Re-load from storage
      const Storage = (await import('@/storage/storage')).default;
      const tenant = await Storage.Tenants.get(res.tenantId!);
      const fleet = await Storage.Fleets.get(res.fleetId!);
      if (tenant) addTenant(tenant);
      if (fleet) addFleet(fleet);
      addAlert({ type: 'success', title: 'Fleet Paired', message: `${details.companyName} connected successfully.` });
      setStep(3);
    } finally { setLoading(false); }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="w-full max-w-md rounded-2xl border border-apex-border bg-apex-card shadow-apex-card animate-fade-in">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-apex-border px-6 py-4">
          <div className="flex items-center gap-2">
            <Shield size={16} className="text-apex-accent" />
            <span className="font-semibold text-apex-text text-sm">Register Fleet Entity</span>
          </div>
          <button onClick={onClose} className="text-apex-textMuted hover:text-apex-text transition-colors">
            <X size={16} />
          </button>
        </div>

        {/* Progress */}
        <div className="flex items-center gap-2 px-6 py-3 border-b border-apex-border/50">
          {[1, 2, 3].map((s) => (
            <React.Fragment key={s}>
              <div className={cn(
                'flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-bold',
                step >= s ? 'bg-apex-accent text-white' : 'bg-apex-border text-apex-textMuted'
              )}>{s}</div>
              {s < 3 && <div className={cn('flex-1 h-0.5', step > s ? 'bg-apex-accent' : 'bg-apex-border')} />}
            </React.Fragment>
          ))}
          <div className="ml-2 text-xs text-apex-textMuted">
            {step === 1 ? 'Enter Code' : step === 2 ? 'Company Details' : 'Complete'}
          </div>
        </div>

        <div className="px-6 py-5 space-y-4">
          {step === 1 && (
            <>
              <p className="text-xs text-apex-textMuted">Enter the registration code generated by your Fleet Control OS installation.</p>
              <div>
                <label className="text-xs font-medium text-apex-textDim uppercase tracking-wider">Pairing Code</label>
                <input
                  value={code}
                  onChange={(e) => setCode(e.target.value.toUpperCase())}
                  placeholder="APEX-XXXXXXXX-XXXX-CC"
                  className="mt-1.5 w-full rounded-lg border border-apex-border bg-apex-surface px-4 py-2.5 font-mono text-sm text-apex-text placeholder:text-apex-textMuted focus:outline-none focus:border-apex-accent/60 transition-colors"
                />
              </div>
              {error && <p className="text-xs text-apex-danger">{error}</p>}
              <button
                onClick={handleInitiate}
                disabled={loading || !code}
                className="w-full rounded-lg bg-apex-accent px-4 py-2.5 text-sm font-semibold text-white hover:bg-apex-accentDim disabled:opacity-50 transition-colors"
              >
                {loading ? 'Validating…' : 'Validate Code'}
              </button>
            </>
          )}

          {step === 2 && (
            <>
              <div className="grid grid-cols-2 gap-3">
                {[
                  { label: 'Company Name', key: 'companyName', type: 'text', placeholder: 'Acme Corp' },
                  { label: 'Contact Email', key: 'contactEmail', type: 'email', placeholder: 'admin@acme.com' },
                  { label: 'Fleet Name', key: 'fleetName', type: 'text', placeholder: 'Main Fleet' },
                  { label: 'Vehicle Count', key: 'vehicleCount', type: 'number', placeholder: '50' },
                ].map((field) => (
                  <div key={field.key} className="col-span-2 sm:col-span-1">
                    <label className="text-xs font-medium text-apex-textDim uppercase tracking-wider">{field.label}</label>
                    <input
                      type={field.type}
                      placeholder={field.placeholder}
                      value={(details as Record<string, unknown>)[field.key] as string}
                      onChange={(e) => setDetails((d) => ({ ...d, [field.key]: field.type === 'number' ? parseInt(e.target.value) : e.target.value }))}
                      className="mt-1.5 w-full rounded-lg border border-apex-border bg-apex-surface px-3 py-2 text-sm text-apex-text placeholder:text-apex-textMuted focus:outline-none focus:border-apex-accent/60 transition-colors"
                    />
                  </div>
                ))}
                <div>
                  <label className="text-xs font-medium text-apex-textDim uppercase tracking-wider">Region</label>
                  <select
                    value={details.region}
                    onChange={(e) => setDetails((d) => ({ ...d, region: e.target.value as RegionCode }))}
                    className="mt-1.5 w-full rounded-lg border border-apex-border bg-apex-surface px-3 py-2 text-sm text-apex-text focus:outline-none focus:border-apex-accent/60"
                  >
                    {['NA', 'EU', 'APAC', 'LATAM', 'MEA'].map((r) => (
                      <option key={r} value={r}>{regionLabel(r)}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="text-xs font-medium text-apex-textDim uppercase tracking-wider">Plan</label>
                  <select
                    value={details.plan}
                    onChange={(e) => setDetails((d) => ({ ...d, plan: e.target.value as 'starter' | 'growth' | 'enterprise' }))}
                    className="mt-1.5 w-full rounded-lg border border-apex-border bg-apex-surface px-3 py-2 text-sm text-apex-text focus:outline-none focus:border-apex-accent/60"
                  >
                    <option value="starter">Starter</option>
                    <option value="growth">Growth</option>
                    <option value="enterprise">Enterprise</option>
                  </select>
                </div>
              </div>
              {error && <p className="text-xs text-apex-danger">{error}</p>}
              <button
                onClick={handleComplete}
                disabled={loading || !details.companyName}
                className="w-full rounded-lg bg-apex-accent px-4 py-2.5 text-sm font-semibold text-white hover:bg-apex-accentDim disabled:opacity-50 transition-colors"
              >
                {loading ? 'Registering…' : 'Complete Registration'}
              </button>
            </>
          )}

          {step === 3 && (
            <div className="flex flex-col items-center gap-4 py-4">
              <div className="flex h-14 w-14 items-center justify-center rounded-full bg-apex-success/10">
                <CheckCircle2 size={28} className="text-apex-success" />
              </div>
              <div className="text-center">
                <p className="font-semibold text-apex-text">{details.companyName} Connected!</p>
                <p className="text-xs text-apex-textMuted mt-1">
                  Fleet entity registered. Telemetry link established.
                </p>
              </div>
              <button
                onClick={() => { onSuccess(); onClose(); }}
                className="rounded-lg bg-apex-success/10 border border-apex-success/30 px-6 py-2 text-sm font-medium text-apex-success hover:bg-apex-success/20 transition-colors"
              >
                View Dashboard
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Tenant Detail Drawer ─────────────────────────────────────────────────────
function TenantDrawer({ tenant, onClose }: { tenant: Tenant; onClose: () => void }) {
  const { fleets, updateTenant, addAlert } = useApexStore();
  const tenantFleets = fleets.filter((f) => f.tenantId === tenant.id);
  const [loading, setLoading] = useState(false);

  const handleSuspend = async () => {
    setLoading(true);
    await suspendTenant(tenant.id, 'Suspended via Command Center');
    updateTenant(tenant.id, { status: 'suspended' });
    addAlert({ type: 'warning', title: 'Tenant Suspended', message: `${tenant.name} has been suspended.` });
    setLoading(false);
    onClose();
  };

  const handleReactivate = async () => {
    setLoading(true);
    await reactivateTenant(tenant.id);
    updateTenant(tenant.id, { status: 'active' });
    addAlert({ type: 'success', title: 'Tenant Reactivated', message: `${tenant.name} is now active.` });
    setLoading(false);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-end bg-black/40 backdrop-blur-sm">
      <div className="h-full w-full max-w-sm border-l border-apex-border bg-apex-card shadow-2xl overflow-y-auto animate-slide-up">
        <div className="flex items-center justify-between border-b border-apex-border px-5 py-4">
          <span className="font-semibold text-apex-text text-sm">{tenant.name}</span>
          <button onClick={onClose} className="text-apex-textMuted hover:text-apex-text"><X size={16} /></button>
        </div>

        <div className="p-5 space-y-5">
          {/* Status */}
          <div className="flex items-center justify-between">
            <StatusBadge status={tenant.status} />
            <span className="text-xs text-apex-textMuted font-mono">{tenant.plan}</span>
          </div>

          {/* Info Grid */}
          {[
            { label: 'Region', value: regionLabel(tenant.region) },
            { label: 'Slug', value: tenant.slug },
            { label: 'Email', value: tenant.contactEmail },
            { label: 'Vehicles', value: formatNumber(tenant.vehicleCount) },
            { label: 'Drivers', value: formatNumber(tenant.driverCount) },
            { label: 'Fleet Count', value: tenant.fleetCount },
            { label: 'Last Seen', value: timeAgo(tenant.lastSeen) },
            { label: 'Created', value: new Date(tenant.createdAt).toLocaleDateString() },
          ].map(({ label, value }) => (
            <div key={label} className="flex items-center justify-between border-b border-apex-border/30 pb-2">
              <span className="text-xs text-apex-textMuted">{label}</span>
              <span className="text-xs text-apex-textDim font-mono">{value}</span>
            </div>
          ))}

          {/* Fleets */}
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-apex-textMuted mb-2">Fleet Entities</p>
            <div className="space-y-2">
              {tenantFleets.map((f) => (
                <div key={f.id} className="flex items-center justify-between rounded-lg bg-apex-surface border border-apex-border/50 px-3 py-2">
                  <div>
                    <p className="text-xs font-medium text-apex-text">{f.name}</p>
                    <p className="text-[10px] text-apex-textMuted">{f.vehicleCount} vehicles · v{f.version}</p>
                  </div>
                  <StatusBadge status={f.status} />
                </div>
              ))}
              {tenantFleets.length === 0 && (
                <p className="text-xs text-apex-textMuted text-center py-3">No fleets</p>
              )}
            </div>
          </div>

          {/* Actions */}
          <div className="space-y-2 pt-2">
            {tenant.status === 'active' ? (
              <button
                onClick={handleSuspend}
                disabled={loading}
                className="w-full rounded-lg border border-apex-danger/40 bg-apex-danger/10 px-4 py-2 text-sm font-medium text-apex-danger hover:bg-apex-danger/20 transition-colors disabled:opacity-50"
              >
                {loading ? 'Processing…' : 'Suspend Tenant'}
              </button>
            ) : tenant.status === 'suspended' && (
              <button
                onClick={handleReactivate}
                disabled={loading}
                className="w-full rounded-lg border border-apex-success/40 bg-apex-success/10 px-4 py-2 text-sm font-medium text-apex-success hover:bg-apex-success/20 transition-colors disabled:opacity-50"
              >
                {loading ? 'Processing…' : 'Reactivate Tenant'}
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function TenantsPage() {
  const { tenants, fleets, isLoading, globalAggregate } = useApexStore();
  const [showPairing, setShowPairing] = useState(false);
  const [selectedTenant, setSelectedTenant] = useState<Tenant | null>(null);
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterRegion, setFilterRegion] = useState<string>('all');

  const filtered = useMemo(() => {
    return tenants.filter((t) => {
      if (filterStatus !== 'all' && t.status !== filterStatus) return false;
      if (filterRegion !== 'all' && t.region !== filterRegion) return false;
      return true;
    });
  }, [tenants, filterStatus, filterRegion]);

  const columns = [
    {
      key: 'name', header: 'Company', sortable: true,
      render: (row: Tenant) => (
        <div>
          <p className="font-medium text-apex-text text-sm">{row.name}</p>
          <p className="text-[10px] text-apex-textMuted font-mono">{row.slug}</p>
        </div>
      ),
    },
    {
      key: 'region', header: 'Region', sortable: true,
      render: (row: Tenant) => (
        <span className="rounded-md border border-apex-border bg-apex-surface px-2 py-0.5 text-xs text-apex-textDim font-mono">
          {row.region}
        </span>
      ),
    },
    {
      key: 'status', header: 'Status',
      render: (row: Tenant) => <StatusBadge status={row.status} />,
    },
    {
      key: 'plan', header: 'Plan',
      render: (row: Tenant) => (
        <span className={cn(
          'text-xs font-medium capitalize',
          row.plan === 'enterprise' ? 'text-apex-purple' :
          row.plan === 'growth' ? 'text-apex-accent' : 'text-apex-textDim'
        )}>{row.plan}</span>
      ),
    },
    {
      key: 'vehicleCount', header: 'Vehicles', sortable: true,
      render: (row: Tenant) => <span className="font-mono text-xs">{formatNumber(row.vehicleCount)}</span>,
    },
    {
      key: 'fleetCount', header: 'Fleets', sortable: true,
      render: (row: Tenant) => {
        const count = fleets.filter((f) => f.tenantId === row.id).length;
        return <span className="font-mono text-xs">{count}</span>;
      },
    },
    {
      key: 'lastSeen', header: 'Last Seen', sortable: true,
      render: (row: Tenant) => <span className="text-xs text-apex-textMuted">{timeAgo(row.lastSeen)}</span>,
    },
    {
      key: 'id', header: '',
      render: (row: Tenant) => (
        <button
          onClick={() => setSelectedTenant(row)}
          className="rounded-lg border border-apex-border px-2.5 py-1 text-xs text-apex-textMuted hover:text-apex-text hover:bg-apex-surface transition-colors flex items-center gap-1"
        >
          Manage <ChevronRight size={12} />
        </button>
      ),
    },
  ];

  return (
    <div className="space-y-6 animate-fade-in">
      {showPairing && (
        <PairingModal onClose={() => setShowPairing(false)} onSuccess={() => {}} />
      )}
      {selectedTenant && (
        <TenantDrawer tenant={selectedTenant} onClose={() => setSelectedTenant(null)} />
      )}

      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-apex-text">
            Tenant <span className="apex-gradient-text">Management</span>
          </h1>
          <p className="text-sm text-apex-textMuted mt-1">Multi-tenant federation registry — isolated environments</p>
        </div>
        <button
          onClick={() => setShowPairing(true)}
          className="flex items-center gap-2 rounded-xl bg-apex-accent px-4 py-2.5 text-sm font-semibold text-white hover:bg-apex-accentDim transition-colors shadow-apex-glow"
        >
          <Plus size={15} /> Register Fleet
        </button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard title="Total Tenants" value={tenants.length} icon={Building2} variant="accent" loading={isLoading} />
        <MetricCard title="Active" value={tenants.filter((t) => t.status === 'active').length} icon={Shield} variant="success" loading={isLoading} />
        <MetricCard title="Suspended" value={tenants.filter((t) => t.status === 'suspended').length} icon={AlertTriangle} variant="danger" loading={isLoading} />
        <MetricCard title="Total Vehicles" value={formatNumber(globalAggregate?.totalVehicles ?? 0)} icon={Truck} variant="purple" loading={isLoading} />
      </div>

      {/* Filters */}
      <div className="flex items-center gap-3 flex-wrap">
        <Globe size={14} className="text-apex-textMuted" />
        {['all', 'NA', 'EU', 'APAC', 'LATAM', 'MEA'].map((r) => (
          <button
            key={r}
            onClick={() => setFilterRegion(r)}
            className={cn(
              'rounded-lg border px-3 py-1 text-xs font-medium transition-colors',
              filterRegion === r
                ? 'border-apex-accent/50 bg-apex-accent/10 text-apex-accent'
                : 'border-apex-border text-apex-textMuted hover:text-apex-text'
            )}
          >{r === 'all' ? 'All Regions' : r}</button>
        ))}
        <div className="ml-auto flex gap-2">
          {['all', 'active', 'suspended', 'pending'].map((s) => (
            <button
              key={s}
              onClick={() => setFilterStatus(s)}
              className={cn(
                'rounded-lg border px-3 py-1 text-xs font-medium transition-colors capitalize',
                filterStatus === s
                  ? 'border-apex-accent/50 bg-apex-accent/10 text-apex-accent'
                  : 'border-apex-border text-apex-textMuted hover:text-apex-text'
              )}
            >{s === 'all' ? 'All Status' : s}</button>
          ))}
        </div>
      </div>

      {/* Table */}
      <div className="rounded-xl border border-apex-border bg-apex-card p-5">
        <DataTable
          columns={columns}
          data={filtered}
          keyField="id"
          searchable
          searchFields={['name', 'slug', 'contactEmail'] as (keyof Tenant)[]}
          loading={isLoading}
          emptyMessage="No tenants found — register your first fleet entity."
          pageSize={15}
        />
      </div>
    </div>
  );
}
