/**
 * AP3X FEDERATION TYPES
 * Types for the multi-fleet registration and monitoring system.
 * These mirror the federation Supabase tables.
 */

// ─────────────────────────────────────────────────────────────────
// TENANTS  — each Fleet Control OS instance registers as a tenant
// ─────────────────────────────────────────────────────────────────
export type TenantStatus = 'active' | 'suspended' | 'pending' | 'offline';
export type TenantPlan = 'starter' | 'growth' | 'enterprise';

export interface Tenant {
  id: string;
  name: string;
  slug: string;
  contact_email: string | null;
  plan: TenantPlan;
  status: TenantStatus;
  region: string | null;
  registered_at: string;
  updated_at: string;
  metadata: Record<string, unknown> | null;
}

// ─────────────────────────────────────────────────────────────────
// FLEET ENTITIES  — each tenant can have multiple fleets
// ─────────────────────────────────────────────────────────────────
export type FleetStatus = 'online' | 'degraded' | 'offline' | 'maintenance';

export interface FleetEntity {
  id: string;
  tenant_id: string;
  name: string;
  version: string | null;
  status: FleetStatus;
  pairing_token: string;           // secret shared key for API auth
  command_center_url: string | null;
  vehicle_count: number;
  active_vehicles: number;
  driver_count: number;
  active_drivers: number;
  uptime_percent: number;
  coordinates: { lat: number; lng: number } | null;
  last_heartbeat: string | null;
  registered_at: string;
  updated_at: string;
}

// ─────────────────────────────────────────────────────────────────
// PAIRING CODES  — short-lived codes generated by Fleet Control OS
// ─────────────────────────────────────────────────────────────────
export type PairingCodeStatus = 'pending' | 'used' | 'expired' | 'locked';

export interface PairingCode {
  id: string;
  code: string;                    // APEX-XXXXXXXX-XXXX-FC
  status: PairingCodeStatus;
  tenant_id: string | null;        // set after pairing
  fleet_id: string | null;         // set after pairing
  attempts: number;
  created_at: string;
  expires_at: string;
  paired_at: string | null;
}

// ─────────────────────────────────────────────────────────────────
// TELEMETRY EVENTS  — batched events from Fleet Control OS
// ─────────────────────────────────────────────────────────────────
export type TelemetryEventType =
  | 'fleet_update' | 'vehicle_event' | 'route_complete'
  | 'ai_inference' | 'api_call' | 'error' | 'alert'
  | 'deployment' | 'heartbeat';

export type TelemetrySeverity = 'info' | 'warning' | 'critical';

export interface TelemetryEvent {
  id: string;
  batch_id: string;
  tenant_id: string;
  fleet_id: string;
  vehicle_id: string | null;
  driver_id: string | null;
  event_type: TelemetryEventType;
  severity: TelemetrySeverity;
  payload: Record<string, unknown>;
  processed: boolean;
  recorded_at: string;
  created_at: string;
}

// ─────────────────────────────────────────────────────────────────
// ROUTE METRICS  — completed route data from fleets
// ─────────────────────────────────────────────────────────────────
export interface RouteMetric {
  id: string;
  tenant_id: string;
  fleet_id: string;
  vehicle_id: string;
  driver_id: string;
  route_id: string;
  distance_km: number;
  duration_min: number;
  fuel_saved_l: number;
  co2_saved_kg: number;
  fuel_cost_saved_usd: number;
  optimisation_saving_percent: number;
  ai_optimised: boolean;
  on_time_delivery: boolean;
  stops: number;
  completed_at: string;
  created_at: string;
}

// ─────────────────────────────────────────────────────────────────
// FLEET HEARTBEAT LOG  — periodic health pings from fleets
// ─────────────────────────────────────────────────────────────────
export interface FleetHeartbeat {
  id: string;
  tenant_id: string;
  fleet_id: string;
  vehicle_count: number;
  active_vehicles: number;
  driver_count: number;
  active_drivers: number;
  uptime_percent: number;
  version: string | null;
  coordinates: { lat: number; lng: number } | null;
  received_at: string;
}

// ─────────────────────────────────────────────────────────────────
// Derived view: tenant with their fleet entities
// ─────────────────────────────────────────────────────────────────
export interface TenantWithFleets extends Tenant {
  fleets: FleetEntity[];
  latest_heartbeat: FleetHeartbeat | null;
  total_vehicles: number;
  total_drivers: number;
  total_routes: number;
  total_co2_saved_kg: number;
}
