-- ============================================================
-- AP3X CONTROL DASHBOARD — FEDERATION SCHEMA
-- Run this in Supabase SQL Editor (Dashboard → SQL → New Query)
-- ============================================================

-- ────────────────────────────────
-- TENANTS
-- Each Fleet Control OS instance = one tenant
-- ────────────────────────────────
create table if not exists tenants (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  slug            text not null unique,
  contact_email   text,
  plan            text not null default 'starter' check (plan in ('starter','growth','enterprise')),
  status          text not null default 'active' check (status in ('active','suspended','pending','offline')),
  region          text,
  metadata        jsonb default '{}',
  registered_at   timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ────────────────────────────────
-- FLEET ENTITIES
-- Each tenant can have multiple fleets
-- ────────────────────────────────
create table if not exists fleet_entities (
  id                  uuid primary key default gen_random_uuid(),
  tenant_id           uuid not null references tenants(id) on delete cascade,
  name                text not null,
  version             text,
  status              text not null default 'online' check (status in ('online','degraded','offline','maintenance')),
  pairing_token       text not null,
  command_center_url  text,
  vehicle_count       integer not null default 0,
  active_vehicles     integer not null default 0,
  driver_count        integer not null default 0,
  active_drivers      integer not null default 0,
  uptime_percent      numeric(5,2) not null default 100,
  coordinates         jsonb,       -- { lat: number, lng: number }
  last_heartbeat      timestamptz,
  registered_at       timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists fleet_entities_tenant_id_idx on fleet_entities(tenant_id);

-- ────────────────────────────────
-- PAIRING CODES
-- Short-lived codes generated by Fleet Control OS
-- ────────────────────────────────
create table if not exists pairing_codes (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,        -- APEX-XXXXXXXX-XXXX-FC
  status      text not null default 'pending' check (status in ('pending','used','expired','locked')),
  tenant_id   uuid references tenants(id) on delete set null,
  fleet_id    uuid references fleet_entities(id) on delete set null,
  attempts    integer not null default 0,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null,
  paired_at   timestamptz
);

create index if not exists pairing_codes_code_idx on pairing_codes(code);
create index if not exists pairing_codes_status_idx on pairing_codes(status);

-- Auto-expire codes after TTL (optional: run via pg_cron)
-- update pairing_codes set status = 'expired' where expires_at < now() and status = 'pending';

-- ────────────────────────────────
-- FLEET HEARTBEATS
-- Periodic health pings from Fleet Control OS
-- ────────────────────────────────
create table if not exists fleet_heartbeats (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references tenants(id) on delete cascade,
  fleet_id        uuid not null references fleet_entities(id) on delete cascade,
  vehicle_count   integer not null default 0,
  active_vehicles integer not null default 0,
  driver_count    integer not null default 0,
  active_drivers  integer not null default 0,
  uptime_percent  numeric(5,2) not null default 100,
  version         text,
  coordinates     jsonb,
  received_at     timestamptz not null default now()
);

create index if not exists fleet_heartbeats_fleet_id_idx on fleet_heartbeats(fleet_id);
create index if not exists fleet_heartbeats_received_at_idx on fleet_heartbeats(received_at desc);

-- ────────────────────────────────
-- TELEMETRY EVENTS
-- Batched events from Fleet Control OS instances
-- ────────────────────────────────
create table if not exists telemetry_events (
  id          text primary key,             -- provided by Fleet Control OS (uuid)
  batch_id    text not null,
  tenant_id   uuid not null references tenants(id) on delete cascade,
  fleet_id    uuid not null references fleet_entities(id) on delete cascade,
  vehicle_id  text,
  driver_id   text,
  event_type  text not null,
  severity    text not null default 'info' check (severity in ('info','warning','critical')),
  payload     jsonb not null default '{}',
  processed   boolean not null default false,
  recorded_at timestamptz not null,
  created_at  timestamptz not null default now()
);

create index if not exists telemetry_events_fleet_id_idx   on telemetry_events(fleet_id);
create index if not exists telemetry_events_tenant_id_idx  on telemetry_events(tenant_id);
create index if not exists telemetry_events_recorded_at_idx on telemetry_events(recorded_at desc);

-- ────────────────────────────────
-- ROUTE METRICS
-- Completed route data from Fleet Control OS instances
-- ────────────────────────────────
create table if not exists route_metrics (
  id                          uuid primary key default gen_random_uuid(),
  tenant_id                   uuid not null references tenants(id) on delete cascade,
  fleet_id                    uuid not null references fleet_entities(id) on delete cascade,
  vehicle_id                  text not null,
  driver_id                   text not null,
  route_id                    text not null unique,
  distance_km                 numeric(10,2) not null default 0,
  duration_min                numeric(10,2) not null default 0,
  fuel_saved_l                numeric(10,3) not null default 0,
  co2_saved_kg                numeric(10,3) not null default 0,
  fuel_cost_saved_usd         numeric(10,2) not null default 0,
  optimisation_saving_percent numeric(5,2)  not null default 0,
  ai_optimised                boolean not null default false,
  on_time_delivery            boolean not null default false,
  stops                       integer not null default 0,
  completed_at                timestamptz not null default now(),
  created_at                  timestamptz not null default now()
);

create index if not exists route_metrics_tenant_id_idx    on route_metrics(tenant_id);
create index if not exists route_metrics_fleet_id_idx     on route_metrics(fleet_id);
create index if not exists route_metrics_completed_at_idx on route_metrics(completed_at desc);

-- ────────────────────────────────
-- ROW LEVEL SECURITY
-- Enable RLS — service role bypasses all policies
-- ────────────────────────────────
alter table tenants          enable row level security;
alter table fleet_entities   enable row level security;
alter table pairing_codes    enable row level security;
alter table fleet_heartbeats enable row level security;
alter table telemetry_events enable row level security;
alter table route_metrics    enable row level security;

-- Allow service role full access (API routes use service role)
-- Public/anon can only read non-sensitive data via the admin app
-- (Admin app uses anon key with RLS policies below)

-- Tenants: readable by authenticated users (admin checks happen in app)
create policy if not exists "tenants_read" on tenants for select using (true);
create policy if not exists "fleet_entities_read" on fleet_entities for select using (true);
create policy if not exists "pairing_codes_read" on pairing_codes for select using (true);
create policy if not exists "fleet_heartbeats_read" on fleet_heartbeats for select using (true);
create policy if not exists "telemetry_events_read" on telemetry_events for select using (true);
create policy if not exists "route_metrics_read" on route_metrics for select using (true);

-- Write policies (for admin dashboard — used via anon key in browser)
create policy if not exists "tenants_insert" on tenants for insert with check (true);
create policy if not exists "tenants_update" on tenants for update using (true);
create policy if not exists "tenants_delete" on tenants for delete using (true);
create policy if not exists "fleet_entities_insert" on fleet_entities for insert with check (true);
create policy if not exists "fleet_entities_update" on fleet_entities for update using (true);
create policy if not exists "fleet_entities_delete" on fleet_entities for delete using (true);
create policy if not exists "pairing_codes_insert" on pairing_codes for insert with check (true);
create policy if not exists "pairing_codes_update" on pairing_codes for update using (true);

-- ────────────────────────────────
-- DONE
-- ────────────────────────────────
-- After running this, add to Vercel:
--   SUPABASE_SERVICE_ROLE_KEY = your-service-role-key (from Supabase → Settings → API)
-- ────────────────────────────────
